### ISSUE TITLE
Numpy compatibility issue

### ISSUE THREAD

**Issue by Midnighter** [biocore/biom-format#974]
When I install biom-format and numpy >= 2 in an environment, I get a lot of errors of the sort:

```
ValueError('numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject')
```

That is even though, version 2.1.16 promises numpy 2.0 compatibility.

I think, the reason is that you do not restrict the numpy version in your build instructions and your wheels are compiled against numpy <2.

```toml
[build-system]
requires = ["setuptools","wheel", "numpy", "cython"]
```
